FROM archlinux:base-20250720.0.386825

RUN pacman -Syu --noconfirm \
  gcc=15.1.1+r7+gf36ec88aa85a-1         \
  gcc-fortran=15.1.1+r7+gf36ec88aa85a-1 \
  openmpi=5.0.8-1                       \
  netcdf=4.9.3                          \
  netcdf-fortran=4.6.1-3                \
  libyaml=0.2.5-3                       \
  autoconf automake git make cmake \
  && find /var/cache/pacman/ -type f -delete
