FROM archlinux:latest

RUN pacman -Syu --noconfirm \
  gcc         \
  gcc-fortran \
  openmpi     \
  netcdf      \
  netcdf-fortran  \
  libyaml         \
  autoconf automake git make cmake \
  && find /var/cache/pacman/ -type f -delete
