# image recipe for fre-cli
# uses gcc + mpich base image on arch linux
# TODO probably better to do miniconda install manually
FROM arch-gnu-openmpi-base

RUN useradd -m -u 1001 -d /home/ci -s /usr/bin/bash ci && \
    pacman -Syu --noconfirm --needed sudo base-devel && \
    echo "ci ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/ci && \
    git clone https://aur.archlinux.org/yay-bin.git && \
    chmod 777 yay-bin

# some extras needed for container building
RUN echo 1 | pacman -Syu --noconfirm \
  fuse-overlayfs \
  podman         \
  apptainer

USER ci

RUN cd yay-bin && makepkg -sri --needed --noconfirm

RUN yay -Syu --noconfirm miniforge

WORKDIR /home/ci
