FROM archlinux:latest

# update keyring and pre-existing packages
RUN pacman-key --init && \
    pacman -Sy --noconfirm --needed archlinux-keyring && \
    pacman --noconfirm -Syyu

# install packages used across CI images
RUN pacman --noconfirm -Syu \
  gcc         \
  gcc-fortran \
  openmpi     \
  netcdf      \
  netcdf-fortran  \
  libyaml         \
  autoconf automake git make cmake \
	inetutils pkgconf zip \
  && find /var/cache/pacman/ -type f -delete
