name: Build and Push CI Images
on: push

jobs:
  build-ci-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v5.0.0
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Build base image
      uses: docker/build-push-action@v6.18.0
      with:
        context: ci/
        push: false
        file: "Dockerfile-base"
    - name: Build fms image
      uses: docker/build-push-action@v6.18.0
      with:
        context: ci/
        push: true
        file: "Dockerfile-fms"
        tag: ghcr.io/noaa-gfdl/fms/fms-ci-gnu:15
    - name: Build fre-nctools image
      uses: docker/build-push-action@v6.18.0
      with:
        context: ci/
        push: false
        file: "Dockerfile-frenct"
        tag: ghcr.io/noaa-gfdl/fre-nctools/frenct-ci-gnu:15
    - name: Build fre-cli image
      uses: docker/build-push-action@v6.18.0
      with:
        context: ci/
        push: false
        file: "Dockerfile-frecli"
        tag: ghcr.io/noaa-gfdl/fre-nctools/frecli-ci-gnu:15
